llm:
  api_type: "open_llm"
  # api_type: "openai"
  base_url: 'http://localhost:5001/forward'
  # model: 'gpt-3.5-turbo'
  # api_type: "openai"  # or ollama  etc.
  # base_url: "https://cfcus02.opapi.win/v1"  # or forward url / other llm url
  model: "llama3.1:8b8k"
  api_key: "sk-XVBaWFFC3af98090Dc32T3BLbkFJ0Ba9481790144B1eaA6B"
  # api_key: "sk-STmQ0VyP26d5093497aET3BLbkFJAB535192D50E4dB8AeC8"

embedding:
  api_type: "hf"  # or  ollama / etc.
  # base_url: "https://cfcus02.opapi.win/v1"  # or forward url / other llm url
  # api_key: "sk-XVBaWFFC3af98090Dc32T3BLbkFJ0Ba9481790144B1eaA6B"
  api_key: "sk-STmQ0VyP26d5093497aET3BLbkFJAB535192D50E4dB8AeC8"
  model: "BAAI/bge-m3"
  cache_dir: ""
  dimensions: 128
  max_token_size: 8102
  embed_batch_size: 128
  embedding_func_max_async: 16

data_root: /mnt/data/wangshu/hcarag/ids_data # Root directory for data
# working_dir: ./test_book # Result directory for the experiment
# exp_name: test_tog # Experiment name

working_dir: /home/yingli/yaodong_codes/GraphRAG/ # Result directory for the experiment
exp_name: yaodong # Experiment name
# 